Updating the example link format from a bare link to a link with link text.
grafana/writers-toolkit pull request #260
Opened 2023-06-06 17:48 UTC by JStickler

The Writer's Toolkit page for [links and cross-references](https://grafana.com/docs/writers-toolkit/writing-guide/references/#understanding-hyperlinks) has a bare URL in the first example:
`For example, https://github.com.`

But all the rest of our link guidance suggests that we do not publish bare URLs, but provide link text.  The Style Guide [section on links](https://grafana.com/docs/writers-toolkit/style-guide/style-conventions/#links-and-references) implies that there should be link text.  As does the [Write useful link text ](https://grafana.com/docs/writers-toolkit/writing-guide/useful-link-text/)topic
`For example, [GitHub](https://github.com]`

2023-06-07 09:03 UTC, jdbaldry commented on docs/sources/writing-guide/references/index.md
> +   For example, `(GitHub)[https://github.com]`.
```suggestion
   For example, `[GitHub](https://github.com)`.
```

2023-06-07 09:04 UTC, jdbaldry requested changes
The Markdown link format is the wrong way around.

2023-06-07 14:53 UTC, JStickler commented
LOL, figures I'd get it backwards!

2023-06-08 11:18 UTC, jdbaldry approved these changes
LGTM now, thanks for fixing!

2023-06-08 14:15 UTC, merged