Add visualization topic examples
grafana/writers-toolkit pull request #736
Opened 2024-06-13 10:34 UTC by jdbaldry

Closes https://github.com/grafana/writers-toolkit/issues/560

Replaces https://github.com/grafana/writers-toolkit/pull/734

2024-06-13 13:34 UTC, imatwawana requested changes
My intent here was to actually have a screenshot. I'll update this when I have some bandwidth next week.

2024-06-13 13:40 UTC, jdbaldry commented
If it changes your mind, this is consistent with the other topics documentation:

- https://grafana.com/docs/writers-toolkit/structure/topic-types/task/#task-topic-examples
- https://grafana.com/docs/writers-toolkit/structure/topic-types/reference/#reference-topic-examples
- https://grafana.com/docs/writers-toolkit/structure/topic-types/concept/#concept-topic-examples

2024-06-19 19:32 UTC, imatwawana approved these changes
I updated the list to use pages that follow the example to a tee

2024-06-19 19:32 UTC, imatwawana commented on docs/sources/structure/topic-types/visualization/index.md
> +- [Time series](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/)
```suggestion
- [Alert list](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/alert-list/)
- [Heatmap](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/heatmap/)
- [Stat](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/stat/)
```

2024-06-19 19:34 UTC, merged